services:
  db:
    image: mysql:8.0
    container_name: todo-reservas-db
    restart: always
    environment:
      MYSQL_DATABASE: todo_reservas
      MYSQL_ROOT_PASSWORD: todo_reservas_password
    ports:
      - "3307:3306"
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: todo-reservas-backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo-reservas-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    container_name: todo-reservas-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"